{
 "title": "Model Dashboard",
 "time": { "from": "now-5m", "to": "now-15s" },
 "refresh": "5s",
 "panels": [
  { "title": "Service Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 1 },
   "options": {
    "content": "# Request Throughput\n\n2xx status codes denote a successful model\nprediction.\n\n4xx status codes are common when clients\nPOST data that does not meet the expected\nschema.\n\nWe calculate the success rate as the percentage\nof HTTP requests that do not return a 5xx code."
   }
  },
  {
   "title": "HTTP Success Rate (30m avg)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(:tensorflow:serving:request_count{model_name=\"tensorflow_model\",status=\"OK\"}[30m])) / sum(rate(:tensorflow:serving:request_count{model_name=\"tensorflow_model\"}[30m]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(:tensorflow:serving:request_count{model_name=\"tensorflow_model\",status=\"OK\"}[1m])) by (status) "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 10 },
   "options": {
    "content": "# Request Latencies\n\nWe have two SLOs for API latency:\n- Average latency SLO is breached if p50\nlatencies exceed 400ms for 5 minutes.\n- Extreme latency SLO is breached if p99\nlatencies exceed 900ms for 5 minutes.        "
   }
  },
  {
   "title": "Requests In Progress",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 5, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(:tensorflow:serving:request_latency_sum{model_name=\"tensorflow_model\"}[1m])/rate(:tensorflow:serving:request_latency_count{model_name=\"tensorflow_model\"}[1m])/1000"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum(\n    rate(:tensorflow:serving:request_latency_bucket{model_name=\"tensorflow_model\",API=\"predict\"}[1m])\n  ) by (le)\n)/1000000",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.90, \n  sum(\n    rate(:tensorflow:serving:request_latency_bucket{model_name=\"tensorflow_model\",API=\"predict\"}[1m])\n  ) by (le)\n)/1000000",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, \n  sum(\n    rate(:tensorflow:serving:request_latency_bucket{model_name=\"tensorflow_model\",API=\"predict\"}[1m])\n  ) by (le)\n)/1000000",
     "legendFormat": "50th percentile"
    }
   ]
  }
 ]
}